### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by 91Abdullah**

### CODE REVIEW

**Comment by opiy-org** [comment]
This will not work.
You should try to delete composer.lock file, run composer update and execute tests.

Woketo and datamapper doesn't support php 8.x (

**Comment by 91Abdullah** [comment]
@opiy-org thanks for your feedback. Just a question that should I remove woketo as a dependency completely? And I know I can't remove datamapper as a dependency because it is used as a conversion mechanism for ARI response to convert into php classes. Only thing I can do is fork the repository change names of Mixed class to something else and publish as a package and include that package into this repo. What do you suggest?

**Comment by opiy-org** [comment]
We can try to use another datamapper, f.e. CuyZ/Valinor or spatie.

I tried but there are a lot of refactoring.

Or... may be there is a chance to update old datamapper to support 8.x

**Comment by 91Abdullah** [comment]
Ok thanks a lot. Let me try to use Valinor package and refactor all the code. Let's see if this works. Also, what do you suggest for woketo? As far as I'm concerned we can safely remove and only use ratchet as a primary websocket implementation. How do you see this?

**Comment by opiy-org** [comment]
Yep, i think we can easliy drop it

**Comment by opiy-org** [comment]
@91Abdullah i've just uploaded v2 branch, it's not finished yet
you can take a look

https://github.com/opiy-org/asterisk-ari-php/tree/v2

**Comment by 91Abdullah** [comment]
@opiy-org as I see it you've already done 80% of work pertaining to refactoring. Do you want me to checkout this branch and work on remaining refactoring?

**Comment by opiy-org** [comment]
i don't think it's 80% )
probably only 20 )

so if you can help - it would be great

**Pull request closed without merging**
